### ISSUE TITLE
Towers

### ISSUE THREAD

**Issue by ftvalex01** [AitorSantaeugenia/Trolls_fangs_and_goblins_TD#9]
You can only select the first 3 towers, the rest won't, or so I think, but it's a great game

**Comment by AitorSantaeugenia** [comment]
The bottom row are placeholders. You can select 3 out of 4 (the fourth one is given when using "whosyourdaddy" cheatcode). 
The bottom row turrets are WIP.

Pierdo mucho tiempo hacer una mierdecita con con GIMP :D.
